tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://www.getcloudify.org/spec/cloudify/4.5/types.yaml
  # For use with a manager use: plugin:cloudify-openstacksdk-plugin
  - plugin.yaml

inputs:

  auth_url:
    type: string

  username:
    type: string

  password:
    type: string

  region_name:
    type: string

  project_name:
    type: string

  project_config:
    default:
      name: 'test_project'
      description: 'Testing Project'
      is_domain': True

dsl_definitions:

  client_config: &client_config
    auth_url: { get_input: auth_url }
    username: { get_input: username }
    password: { get_input: password }
    region_name: { get_input: region_name }
    project_name: { get_input: project_name }

node_templates:

  example-project:
    type: cloudify.nodes.openstack.Project
    properties:
      client_config: *client_config
      resource_config: { get_input: project_config }
      # Users & roles must be exist, otherwise the install workflow will fail
      users:
        - name: test_user
          roles:
            - test_role_1
            - test_role_2
            - test_role_3