version: 2
checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi
jobs:
  unittests:
    docker:
      - image: circleci/python:2.7.15-stretch
    steps:
      - checkout
      - run:
          name: Running Unit Tests
          command: |
            curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
            sudo python get-pip.py
            pip install --user virtualenv
            virtualenv env
            source env/bin/activate
            pip install tox
            tox -e flake8
            tox -e py27
workflows:
  version: 2
  tests:
    jobs:
      - unittests
  nightly:
    triggers:
    - schedule:
        cron: "0 0 * * *"
        filters:
          branches:
            only:
              - dev
    jobs:
      - unittests
